# Generated by Django 3.1.4 on 2022-09-06 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visiting_card',
            name='card_cat',
            field=models.CharField(choices=[('General', 'General'), ('Health & Care', 'Health & Care'), ('Construct & Real Estate', 'Construction & Real Estate'), ('Fashion', 'Fashion'), ('Legal', 'Legal'), ('Beauty Shop', 'Beauty Shop'), ('Manufacturing', 'Manufacturing'), ('Automobile', 'Automobile'), ('Print & Technology', 'Print & Technology'), ('Food & Restraunt', 'Food & Restraunt'), ('Education', 'Education'), ('Tour & Travels', 'Tour & Travels')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='visiting_card',
            name='card_price',
            field=models.IntegerField(default=300),
        ),
    ]
