# Generated by Django 3.1.4 on 2022-09-06 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220906_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='brochure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bro_name', models.CharField(default='', max_length=30)),
                ('bro_art_paper', models.IntegerField(default=100)),
                ('bro_price', models.IntegerField(default=300)),
                ('bro_image', models.ImageField(default='', upload_to='cards/')),
            ],
        ),
        migrations.CreateModel(
            name='envelope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('env_name', models.CharField(default='', max_length=30)),
                ('env_size', models.CharField(choices=[('A4', 'A4')], default='A4', max_length=5)),
                ('env_cat', models.CharField(choices=[('Doctors', 'Doctors')], default='Doctors', max_length=25)),
                ('env_price', models.IntegerField(default=300)),
                ('env_image', models.ImageField(default='', upload_to='cards/')),
            ],
        ),
        migrations.CreateModel(
            name='letter_head',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lh_name', models.CharField(default='', max_length=30)),
                ('lh_qual', models.CharField(choices=[('matte', 'matte'), ('Bond', 'Bond')], default='matte', max_length=20)),
                ('lh_size', models.CharField(choices=[('A4', 'A4')], default='A4', max_length=5)),
                ('lh_price', models.IntegerField(default=300)),
                ('lh_image', models.ImageField(default='', upload_to='cards/')),
            ],
        ),
    ]
