# Generated by Django 3.1.4 on 2022-09-06 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_brochure_envelope_letter_head'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brochure',
            name='bro_image',
            field=models.ImageField(default='', upload_to='Brochure/'),
        ),
        migrations.AlterField(
            model_name='envelope',
            name='env_image',
            field=models.ImageField(default='', upload_to='Envelope/'),
        ),
        migrations.AlterField(
            model_name='letter_head',
            name='lh_image',
            field=models.ImageField(default='', upload_to='Letter Heads/'),
        ),
        migrations.AlterField(
            model_name='visiting_card',
            name='card_image',
            field=models.ImageField(default='', upload_to='Visiting Cards/'),
        ),
    ]
