# Generated by Django 3.1.4 on 2022-09-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20220906_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(default='', max_length=40)),
                ('c_phone', models.IntegerField(default=0)),
                ('msg', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
