# Generated by Django 3.1.4 on 2022-09-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='c_mail',
            field=models.CharField(default='', max_length=30),
        ),
    ]
